package com.shop.domain;
// Generated Mar 31, 2020 7:37:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String name;
     private String status;
     private Set<Shop> shops = new HashSet<Shop>(0);

    public Category() {
    }

    public Category(String code, String name, String status, Set<Shop> shops) {
       this.code = code;
       this.name = name;
       this.status = status;
       this.shops = shops;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Shop> getShops() {
        return this.shops;
    }
    
    public void setShops(Set<Shop> shops) {
        this.shops = shops;
    }




}


