package com.shop.domain;
// Generated Mar 30, 2020 7:29:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String name;
     private String description;
     private String status;
     private Set<PackageHasItem> packageHasItems = new HashSet<PackageHasItem>(0);

    public Item() {
    }

    public Item(String code, String name, String description, String status, Set<PackageHasItem> packageHasItems) {
       this.code = code;
       this.name = name;
       this.description = description;
       this.status = status;
       this.packageHasItems = packageHasItems;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<PackageHasItem> getPackageHasItems() {
        return this.packageHasItems;
    }
    
    public void setPackageHasItems(Set<PackageHasItem> packageHasItems) {
        this.packageHasItems = packageHasItems;
    }




}


