package com.shop.domain;
// Generated Mar 30, 2020 7:29:02 PM by Hibernate Tools 4.3.1



/**
 * PackageHasItem generated by hbm2java
 */
public class PackageHasItem  implements java.io.Serializable {


     private PackageHasItemId id;
     private Item item;
     private PackageN packageN;
     private Integer qtyG;

    public PackageHasItem() {
    }

	
    public PackageHasItem(PackageHasItemId id, Item item, PackageN packageN) {
        this.id = id;
        this.item = item;
        this.packageN = packageN;
    }
    public PackageHasItem(PackageHasItemId id, Item item, PackageN packageN, Integer qtyG) {
       this.id = id;
       this.item = item;
       this.packageN = packageN;
       this.qtyG = qtyG;
    }
   
    public PackageHasItemId getId() {
        return this.id;
    }
    
    public void setId(PackageHasItemId id) {
        this.id = id;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public PackageN getPackageN() {
        return this.packageN;
    }
    
    public void setPackageN(PackageN packageN) {
        this.packageN = packageN;
    }
    public Integer getQtyG() {
        return this.qtyG;
    }
    
    public void setQtyG(Integer qtyG) {
        this.qtyG = qtyG;
    }




}


