package com.shop.domain;
// Generated Mar 31, 2020 7:37:15 AM by Hibernate Tools 4.3.1



/**
 * PackageHasItemId generated by hbm2java
 */
public class PackageHasItemId  implements java.io.Serializable {


     private int packageId;
     private int itemId;

    public PackageHasItemId() {
    }

    public PackageHasItemId(int packageId, int itemId) {
       this.packageId = packageId;
       this.itemId = itemId;
    }
   
    public int getPackageId() {
        return this.packageId;
    }
    
    public void setPackageId(int packageId) {
        this.packageId = packageId;
    }
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PackageHasItemId) ) return false;
		 PackageHasItemId castOther = ( PackageHasItemId ) other; 
         
		 return (this.getPackageId()==castOther.getPackageId())
 && (this.getItemId()==castOther.getItemId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPackageId();
         result = 37 * result + this.getItemId();
         return result;
   }   


}


