package com.shop.domain;
// Generated Mar 30, 2020 7:29:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Shop generated by hbm2java
 */
public class Shop  implements java.io.Serializable {


     private Integer id;
     private Area area;
     private Category category;
     private UserDetails userDetails;
     private String brNo;
     private Character is24Hours;
     private Integer deliveryTimeMin;
     private Integer deliveryTimeMax;
     private String contactNo1;
     private String contactNo2;
     private String whatsappViber;
     private String email;
     private String address;
     private String status;
     private Double deliveryKm;
     private String website;
     private String fbLink;
     private String name;
     private String otherName;
     private Date createdDate;
     private Date from;
     private Date to;
     private Set<Area> areas = new HashSet<Area>(0);
     private Set<PackageN> packageNs = new HashSet<PackageN>(0);

    public Shop() {
    }

	
    public Shop(Area area, Category category, UserDetails userDetails) {
        this.area = area;
        this.category = category;
        this.userDetails = userDetails;
    }
    public Shop(Area area, Category category, UserDetails userDetails, String brNo, Character is24Hours, Integer deliveryTimeMin, Integer deliveryTimeMax, String contactNo1, String contactNo2, String whatsappViber, String email, String address, String status, Double deliveryKm, String website, String fbLink, String name, String otherName, Date createdDate, Date from, Date to, Set<Area> areas, Set<PackageN> packageNs) {
       this.area = area;
       this.category = category;
       this.userDetails = userDetails;
       this.brNo = brNo;
       this.is24Hours = is24Hours;
       this.deliveryTimeMin = deliveryTimeMin;
       this.deliveryTimeMax = deliveryTimeMax;
       this.contactNo1 = contactNo1;
       this.contactNo2 = contactNo2;
       this.whatsappViber = whatsappViber;
       this.email = email;
       this.address = address;
       this.status = status;
       this.deliveryKm = deliveryKm;
       this.website = website;
       this.fbLink = fbLink;
       this.name = name;
       this.otherName = otherName;
       this.createdDate = createdDate;
       this.from = from;
       this.to = to;
       this.areas = areas;
       this.packageNs = packageNs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public UserDetails getUserDetails() {
        return this.userDetails;
    }
    
    public void setUserDetails(UserDetails userDetails) {
        this.userDetails = userDetails;
    }
    public String getBrNo() {
        return this.brNo;
    }
    
    public void setBrNo(String brNo) {
        this.brNo = brNo;
    }
    public Character getIs24Hours() {
        return this.is24Hours;
    }
    
    public void setIs24Hours(Character is24Hours) {
        this.is24Hours = is24Hours;
    }
    public Integer getDeliveryTimeMin() {
        return this.deliveryTimeMin;
    }
    
    public void setDeliveryTimeMin(Integer deliveryTimeMin) {
        this.deliveryTimeMin = deliveryTimeMin;
    }
    public Integer getDeliveryTimeMax() {
        return this.deliveryTimeMax;
    }
    
    public void setDeliveryTimeMax(Integer deliveryTimeMax) {
        this.deliveryTimeMax = deliveryTimeMax;
    }
    public String getContactNo1() {
        return this.contactNo1;
    }
    
    public void setContactNo1(String contactNo1) {
        this.contactNo1 = contactNo1;
    }
    public String getContactNo2() {
        return this.contactNo2;
    }
    
    public void setContactNo2(String contactNo2) {
        this.contactNo2 = contactNo2;
    }
    public String getWhatsappViber() {
        return this.whatsappViber;
    }
    
    public void setWhatsappViber(String whatsappViber) {
        this.whatsappViber = whatsappViber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Double getDeliveryKm() {
        return this.deliveryKm;
    }
    
    public void setDeliveryKm(Double deliveryKm) {
        this.deliveryKm = deliveryKm;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getFbLink() {
        return this.fbLink;
    }
    
    public void setFbLink(String fbLink) {
        this.fbLink = fbLink;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getOtherName() {
        return this.otherName;
    }
    
    public void setOtherName(String otherName) {
        this.otherName = otherName;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getFrom() {
        return this.from;
    }
    
    public void setFrom(Date from) {
        this.from = from;
    }
    public Date getTo() {
        return this.to;
    }
    
    public void setTo(Date to) {
        this.to = to;
    }
    public Set<Area> getAreas() {
        return this.areas;
    }
    
    public void setAreas(Set<Area> areas) {
        this.areas = areas;
    }
    public Set<PackageN> getPackageNs() {
        return this.packageNs;
    }
    
    public void setPackageNs(Set<PackageN> packageNs) {
        this.packageNs = packageNs;
    }




}


