package com.shop.domain;
// Generated Mar 31, 2020 7:37:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserLevel generated by hbm2java
 */
public class UserLevel  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String name;
     private String status;
     private Set<UserDetails> userDetailses = new HashSet<UserDetails>(0);

    public UserLevel() {
    }

    public UserLevel(String code, String name, String status, Set<UserDetails> userDetailses) {
       this.code = code;
       this.name = name;
       this.status = status;
       this.userDetailses = userDetailses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<UserDetails> getUserDetailses() {
        return this.userDetailses;
    }
    
    public void setUserDetailses(Set<UserDetails> userDetailses) {
        this.userDetailses = userDetailses;
    }




}


